### ISSUE TITLE
use glew 

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/cygl#1]
without GLEW we have portability trouble

**Comment by mkassner** [comment]
This also means we have to make our own glfw bindings that use include glew.

**Comment by mkassner** [comment]
implemented for mac and linux. MichaelBarz can you check for windows?

**Comment by mkassner** [comment]
Concerning comment#2. This turns out to be not true. Works just fine with the normal glfw python bindings.

**Comment by MichaelBarz** [comment]
builds on windows when adding openGL as lib

**Comment by mkassner** [comment]
Implemented
