### ISSUE TITLE
windows wheels

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/cygl#4]
@MichaelBarz after thinking about this again. Please remove the wheel and dist dir from the repo. Instead make a tag, and upload the wheel to in the release page. Then update the install instructions and point to the download link.

**Comment by MichaelBarz** [comment]
Currently there is no wheel for cygl. It gets installed by installing pyglui.
Shall I add a wheel?

**Comment by mkassner** [comment]
no, sorry no need for a wheel in cygl.

**Comment by MichaelBarz** [comment]
Ok ;)
